namespace: t_systems_mms
name: icinga_business_process
version: 1.0.4
readme: README.md
authors:
  - Christoph Sieber <christoph.sieber@t-systems.com>
  - Daniel Uhlmann <daniel.uhlmann@t-systems.com>
description: >-
  This collection contains an Ansible role to configure business processes in
  the icinga business process extension.
license:
  - GPL-3.0-only
license_file: ''
tags:
  - icinga
  - monitoring
  - business_process
dependencies: {}
repository: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-business-process'
documentation: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-business-process'
homepage: 'https://github.com/T-Systems-MMS/ansible-collection-icinga-business-process'
issues: >-
  https://github.com/T-Systems-MMS/ansible-collection-icinga-business-process/issues
build_ignore:
  - .github
