---
collections:
  - telekom_mms.icinga_business_process
galaxy_info:
  author: telekom_mms
  description: icinga business process configuration
  license: GPLv3
  min_ansible_version: 2.9
  galaxy_tags:
    - icinga
