---

- name: check if business process already exists
  uri:
    url: "{{ icinga_business_process_url }}/businessprocess/process/show?config={{ item.title }}&format=json"
    user: "{{ icinga_business_process_user }}"
    password: "{{ icinga_business_process_password }}"
    force_basic_auth: "{{ icinga_business_process_force_basic_auth | default(omit) }}"
    method: GET
    status_code:
      - 404
      - 200
  register: alreadyexists

- name: download configuration of existing business process
  uri:
    url: "{{ icinga_business_process_url }}/businessprocess/process/download?config={{ item.title }}"
    user: "{{ icinga_business_process_user }}"
    password: "{{ icinga_business_process_password }}"
    force_basic_auth: "{{ icinga_business_process_force_basic_auth | default(omit) }}"
    method: GET
    return_content: true
  when: alreadyexists.status == 200
  register: configuration_download

- name: cleanup downloaded process configuration
  set_fact:
    dl_cleanup: "{{ configuration_download.content | replace('\n\n\n', '\n') | replace('\n\n', '\n') }}"
  when: alreadyexists.status == 200 and configuration_download.content is defined

- name: cleanup business process configuration
  set_fact:
    template_cleanup: "{{ lookup('template', './config.j2', convert_data=False) | replace('\n\n', '\n') }}"

- name: delete existing business process if it exists
  uri:
    url: "{{ icinga_business_process_url }}/businessprocess/process/config?config={{ item.title }}"
    user: "{{ icinga_business_process_user }}"
    password: "{{ icinga_business_process_password }}"
    force_basic_auth: "{{ icinga_business_process_force_basic_auth | default(omit) }}"
    method: POST
    body_format: form-urlencoded
    body:
      __FORM_NAME: IcingaModuleBusinessprocessFormsBpConfigForm
      name: "{{ item.title }}"
      Title: "{{ item.title }}"
      Delete: Delete
    status_code:
      - 302
  when: >
    alreadyexists.status == 200 and
    dl_cleanup != template_cleanup

- name: upload template
  uri:
    url: "{{ icinga_business_process_url }}/businessprocess/process/upload"
    user: "{{ icinga_business_process_user }}"
    password: "{{ icinga_business_process_password }}"
    force_basic_auth: "{{ icinga_business_process_force_basic_auth | default(omit) }}"
    method: POST
    status_code:
      - 302
    body_format: form-urlencoded
    body:
      name: '{{ item.title }}'
      source: "{{ lookup('template', './config.j2', convert_data=False) }}"
      Store: Store
      __FORM_NAME: IcingaModuleBusinessprocessFormsBpUploadForm
  register: upload
  retries: 10
  delay: 10
  until: upload.status == 302
  when: >
    (
      alreadyexists.status == 200 and
      dl_cleanup != template_cleanup
    ) or
    alreadyexists.status == 404
